name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train model
        run: python src/train.py

      - name: Predict
        run: python src/predict.py

      # - name: Build Docker Image
      #   if: success()
      #   run: |
      #     docker build -t my_model_image .

      # - name: Push Docker image to registry
      #   if: success()
      #   run: |
      #     docker tag my_model_image docker-registry/my_model_image:latest
      #     docker push docker-registry/my_model_image:latest